import re
from difflib import SequenceMatcher


class DocumentVerifier:

    def __init__(self, threshold=0.70):
        self.threshold = threshold

    # Clean text before comparison
    def clean_text(self, text):
        text = text.lower()
        text = re.sub(r'\s+', ' ', text)
        text = re.sub(r'[^\w\s.%/-]', '', text)
        return text.strip()

    # Calculate similarity between two statements
    def similarity(self, text1, text2):
        text1 = self.clean_text(text1)
        text2 = self.clean_text(text2)

        return SequenceMatcher(None, text1, text2).ratio()

    # Extract simple factual sentences from source
    def extract_facts(self, source_text):
        sentences = re.split(r'[.!?]\s+', source_text)

        facts = []

        for sentence in sentences:
            sentence = sentence.strip()

            if len(sentence) > 15:
                facts.append(sentence)

        return facts

    # Find best matching source fact for a generated claim
    def find_best_match(self, claim, source_facts):

        best_fact = None
        best_score = 0

        for fact in source_facts:

            score = self.similarity(claim, fact)

            if score > best_score:
                best_score = score
                best_fact = fact

        return best_fact, best_score

    # Verify generated claims
    def verify_claims(self, source_text, generated_claims):

        source_facts = self.extract_facts(source_text)

        results = []

        for claim in generated_claims:

            best_fact, score = self.find_best_match(
                claim,
                source_facts
            )

            if score >= self.threshold:

                status = "VERIFIED"

            elif score >= 0.45:

                status = "PARTIAL MATCH"

            else:

                status = "CONTENT DRIFT"

            results.append({
                "claim": claim,
                "source_reference": best_fact,
                "similarity_score": round(score, 2),
                "status": status
            })

        return results
    # Verify content generated by the AI
    def verify_generated_content(self, source_text, generated_content):

        generated_claims = self.extract_facts(generated_content)

        return self.verify_claims(
            source_text,
            generated_claims
        )

# --------------------------------------------------
# Example Usage
# --------------------------------------------------

if __name__ == "__main__":

    source_document = """
    Artificial intelligence is used in healthcare.
    AI can help doctors analyze medical images.
    Machine learning can detect patterns in patient data.
    AI systems can support doctors in making decisions.
    """

    generated_claims = [
        "Artificial intelligence is used in healthcare.",
        "AI can analyze medical images.",
        "AI completely replaces doctors.",
        "Machine learning detects patterns in patient data."
    ]

    verifier = DocumentVerifier(threshold=0.70)

    report = verifier.verify_claims(
        source_document,
        generated_claims
    )

    print("\n===== DOCUMENT VERIFICATION REPORT =====\n")

    for item in report:

        print("Claim:", item["claim"])
        print("Source:", item["source_reference"])
        print("Similarity:", item["similarity_score"])
        print("Status:", item["status"])
        print("-" * 50)